<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Yandex Market");
?><?global $arrFilter;
$arrFilter=array("!PROPERTY_WF_NO_YM_VALUE"=>"Y");?>
<noindex><?$APPLICATION->IncludeComponent(
	"webfly:yandex.market", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"AGENT_CHECK" => "Y",
		"IBLOCK_TYPE_LIST" => array(
			0 => "1c_catalog",
		),
		"SAVE_IN_FILE" => "Y",
		"IBLOCK_CATALOG" => "N",
		"IBLOCK_ID_IN" => array(
			0 => "12",
		),
		"IBLOCK_SECTION" => array(
			0 => "1267",
			1 => "1311",
			2 => "1314",
			3 => "1315",
			4 => "1318",
			5 => "1321",
			6 => "1324",
			7 => "1327",
			8 => "1328",
			9 => "1331",
			10 => "1334",
			11 => "1337",
			12 => "1338",
			13 => "1339",
			14 => "1342",
			15 => "1345",
			16 => "1347",
			17 => "1348",
			18 => "1349",
			19 => "1352",
			20 => "1354",
			21 => "1355",
			22 => "1356",
			23 => "1358",
			24 => "1359",
			25 => "1670",
			26 => "1671",
			27 => "1672",
			28 => "1673",
			29 => "1674",
			30 => "1683",
			31 => "1702",
			32 => "1723",
		),
		"DO_NOT_INCLUDE_SUBSECTIONS" => "N",
		"IBLOCK_AS_CATEGORY" => "Y",
		"BIG_CATALOG_PROP" => "500",
		"HTTPS_CHECK" => "N",
		"SITE" => "bigms.ru",
		"COMPANY" => "Большой мастер",
		"FILTER_NAME" => "arrFilter",
		"MORE_PHOTO" => "Детальная картинка",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_NON_MANAGED" => "N",
		"CACHE_FILTER" => "N",
		"SKU_NAME" => "PRODUCT_NAME",
		"SKU_PROPERTY" => "",
		"SALES_NOTES" => "0",
		"SALES_NOTES_TEXT" => "Гарантия производителя",
		"OLD_PRICE" => "N",
		"PRICE_ROUND" => "Y",
		"PRICE_CODE" => array(
			0 => "Интернет",
		),
		"IBLOCK_ORDER" => "Y",
		"AVAILABLE_ALGORITHM" => "QUANTITY_ZERO",
		"CURRENCIES_CONVERT" => "NOT_CONVERT",
		"LOCAL_DELIVERY_COST" => "",
		"DELIVERY_OPTIONS_SHOP_EX" => "500,2,",
		"LOCAL_DELIVERY_COST_OFFER" => "0",
		"DELIVERY_OPTIONS_EX" => "YA_STOIMOST_DOSTAVKI,YA_SROK_DOSTAVKI,",
		"STORE_OFFER" => "true",
		"STORE_PICKUP" => "true",
		"NAME_PROP" => "0",
		"NAME_PROP_COMPILE" => "",
		"NAME_CUT" => "",
		"PROPDUCT_PROP" => array(
		),
		"OFFER_PROP" => array(
		),
		"PREFIX_PROP" => "0",
		"DESCRIPTION" => "0",
		"DETAIL_TEXT_PRIORITET" => "N",
		"NO_DESCRIPTION" => "N",
		"AGE_CATEGORY" => "0",
		"AGE_CATEGORY_UNIT" => "year",
		"BID" => "0",
		"CBID" => "0",
		"CPA_SHOP" => "",
		"CPA_OFFERS" => "0",
		"EXPIRY" => "0",
		"WEIGHT" => "0",
		"DIMENSIONS" => "0",
		"PARAMS" => array(
			0 => "STRANA_PROIZVODITEL",
		),
		"COND_PARAMS" => array(
			0 => "BREND",
			1 => "CML2_MANUFACTURER",
			2 => "DIZAYN",
			3 => "GARANTIYA_LET",
			4 => "MATERIAL",
			5 => "STILISTIKA_DIZAYNA",
			6 => "STRANA_PROIZVODITEL",
			7 => "TIP_IZDELIYA",
			8 => "TIP_MONTAZHA",
		),
		"DISCOUNTS" => "DISCOUNT_API",
		"UTM_CHECK" => "Y",
		"UTM_SOURCE" => "YandexMarket",
		"UTM_CAMPAIGN" => "",
		"UTM_MEDIUM" => "cpc",
		"UTM_TERM" => "",
		"MARKET_CATEGORY_PROP" => "0",
		"DEVELOPER" => "BREND",
		"VENDOR_CODE" => "ARTIKUL",
		"COUNTRY" => "0",
		"MANUFACTURER_WARRANTY" => "0",
		"BRANDS_TOMORROW" => array(
		),
		"BRANDS_FREE" => array(
		),
		"BRANDS_300" => array(
		),
		"BRANDS_AVAILABLE" => array(
		),
		"SECTION_AS_VENDOR" => "N",
		"MULTI_STRING_PROP" => "",
		"CATEGORY" => "DEFAULT_CATEGORY",
		"MARKET_CATEGORY_CHECK" => "N",
		"CATEGORY_NAME_PROPERTY" => "",
		"DELIVERY_TO_AVAILABLE" => "N",
		"STORE_DELIVERY" => "",
		"OUTLETS" => "",
		"FEE" => "0",
		"RECOMMENDATION" => "0",
		"ADULT_ALL" => "N",
		"ADULT" => "",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false
);?></noindex><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>